# Additional 50 competitors data - Part 2 (25 more competitors)
# Organized by Certify Health competitive categories

ADDITIONAL_COMPETITORS_PART2 = [
    # ===== ELIGIBILITY / INSURANCE VERIFICATION COMPETITORS =====
    {
        "name": "Pverify",
        "website": "https://www.pverify.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Per Transaction",
        "base_price": "$0.15",
        "price_unit": "per verification",
        "product_categories": "Eligibility; Insurance Verification",
        "key_features": "Real-time eligibility, Benefits check, Prior auth, Batch processing",
        "integration_partners": "Multiple PM/EHR systems",
        "certifications": "HIPAA",
        "target_segments": "Specialty; Dental; Medical",
        "customer_size_focus": "Small (1-15)",
        "geographic_focus": "US National",
        "customer_count": "5000+",
        "customer_acquisition_rate": "Growing",
        "key_customers": "Dental and medical practices",
        "g2_rating": "4.5",
        "employee_count": "100+",
        "employee_growth_rate": "25% YoY",
        "year_founded": "2013",
        "headquarters": "Frisco, TX",
        "funding_total": "$15M+",
        "latest_round": "Series A",
        "pe_vc_backers": "VC Backed",
        "website_traffic": "50K+",
        "social_following": "5K+",
        "recent_launches": "AI eligibility",
        "news_mentions": "8",
    },
    {
        "name": "Verisma",
        "website": "https://verisma.com",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Per Transaction",
        "base_price": "$1.50",
        "price_unit": "per request",
        "product_categories": "Health Information; ROI",
        "key_features": "Release of information, Record retrieval, Compliance",
        "integration_partners": "EHR systems",
        "certifications": "HIPAA",
        "target_segments": "Health Systems; Hospitals",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "500+",
        "customer_acquisition_rate": "Steady",
        "key_customers": "Health systems",
        "g2_rating": "3.8",
        "employee_count": "200+",
        "employee_growth_rate": "10% YoY",
        "year_founded": "1986",
        "headquarters": "Indianapolis, IN",
        "funding_total": "Private",
        "latest_round": "Private",
        "pe_vc_backers": "Private",
        "website_traffic": "10K+",
        "social_following": "2K+",
        "recent_launches": "Digital ROI",
        "news_mentions": "3",
    },
    {
        "name": "Surescripts",
        "website": "https://surescripts.com",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Transaction",
        "base_price": "Variable",
        "price_unit": "per transaction",
        "product_categories": "E-Prescribing; Clinical Data; Eligibility",
        "key_features": "E-prescribing network, Clinical history, Eligibility, Medication history",
        "integration_partners": "All major EHRs; Pharmacies",
        "certifications": "HIPAA; SOC2",
        "target_segments": "EHR vendors; Pharmacies; Payers",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "Network of 2M+ clinicians",
        "customer_acquisition_rate": "Established",
        "key_customers": "All major EHRs",
        "g2_rating": "4.0",
        "employee_count": "600+",
        "employee_growth_rate": "5% YoY",
        "year_founded": "2001",
        "headquarters": "Arlington, VA",
        "funding_total": "Private (Industry consortium)",
        "latest_round": "N/A",
        "pe_vc_backers": "Industry consortium",
        "website_traffic": "100K+",
        "social_following": "10K+",
        "recent_launches": "Real-time benefits",
        "news_mentions": "25",
    },
    {
        "name": "CoverMyMeds",
        "website": "https://covermymeds.com",
        "status": "Acquired",
        "threat_level": "Low",
        "pricing_model": "Free to Prescribers",
        "base_price": "Free",
        "price_unit": "payer-funded",
        "product_categories": "Prior Authorization; E-Prescribing",
        "key_features": "Electronic prior auth, Prescription savings, Network of payers",
        "integration_partners": "Major EHRs; PBMs",
        "certifications": "HIPAA",
        "target_segments": "Prescribers; Pharmacies; Payers",
        "customer_size_focus": "All Sizes",
        "geographic_focus": "US National",
        "customer_count": "750K+ providers",
        "customer_acquisition_rate": "Strong",
        "key_customers": "Prescribers nationwide",
        "g2_rating": "4.2",
        "employee_count": "1000+",
        "employee_growth_rate": "Acquired",
        "year_founded": "2008",
        "headquarters": "Columbus, OH",
        "funding_total": "Acquired by McKesson",
        "latest_round": "Acquired",
        "pe_vc_backers": "McKesson",
        "website_traffic": "1M+",
        "social_following": "25K+",
        "recent_launches": "Real-time PA",
        "news_mentions": "30",
    },
    # ===== DIGITAL FRONT DOOR / ACCESS COMPETITORS =====
    {
        "name": "Bright.md",
        "website": "https://bright.md",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Per Visit",
        "base_price": "$25",
        "price_unit": "per clinical interview",
        "product_categories": "Digital Front Door; Asynchronous Care",
        "key_features": "Asynchronous virtual care, AI clinical interviews, Triage",
        "integration_partners": "Epic; Cerner",
        "certifications": "HIPAA; SOC2",
        "target_segments": "Health Systems; Employers",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "40+",
        "customer_acquisition_rate": "Growing",
        "key_customers": "Intermountain; Ochsner",
        "g2_rating": "4.5",
        "employee_count": "100+",
        "employee_growth_rate": "20% YoY",
        "year_founded": "2014",
        "headquarters": "Portland, OR",
        "funding_total": "$60M+",
        "latest_round": "Series C",
        "pe_vc_backers": "Mosaic Health Solutions",
        "website_traffic": "20K+",
        "social_following": "5K+",
        "recent_launches": "SmartExam expansion",
        "news_mentions": "10",
    },
    {
        "name": "Fabric (formerly Zipnosis)",
        "website": "https://www.fabrichealth.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Enterprise",
        "base_price": "Custom",
        "price_unit": "enterprise pricing",
        "product_categories": "Virtual Care; Digital Front Door",
        "key_features": "Adaptive clinical interviews, Virtual care, Triage, Care navigation",
        "integration_partners": "Epic; Cerner",
        "certifications": "HIPAA; SOC2",
        "target_segments": "Health Systems",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "70+",
        "customer_acquisition_rate": "Growing",
        "key_customers": "SSM Health; Fairview",
        "g2_rating": "4.3",
        "employee_count": "150+",
        "employee_growth_rate": "30% YoY",
        "year_founded": "2012",
        "headquarters": "Minneapolis, MN",
        "funding_total": "$80M+",
        "latest_round": "Series D",
        "pe_vc_backers": "OSF Ventures",
        "website_traffic": "15K+",
        "social_following": "3K+",
        "recent_launches": "AI navigation",
        "news_mentions": "15",
    },
    {
        "name": "GetWellNetwork",
        "website": "https://getwellnetwork.com",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Enterprise",
        "base_price": "Custom",
        "price_unit": "enterprise pricing",
        "product_categories": "Patient Engagement; Bedside Entertainment",
        "key_features": "Inpatient engagement, Care coordination, Patient education, Entertainment",
        "integration_partners": "Major EHRs",
        "certifications": "HIPAA",
        "target_segments": "Hospitals; Health Systems",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "500+",
        "customer_acquisition_rate": "Steady",
        "key_customers": "Major hospital systems",
        "g2_rating": "4.0",
        "employee_count": "300+",
        "employee_growth_rate": "10% YoY",
        "year_founded": "1999",
        "headquarters": "Bethesda, MD",
        "funding_total": "$100M+",
        "latest_round": "PE Backed",
        "pe_vc_backers": "Marlin Equity",
        "website_traffic": "30K+",
        "social_following": "5K+",
        "recent_launches": "GetWell Loop+",
        "news_mentions": "12",
    },
    # ===== SCHEDULING / ACCESS MANAGEMENT COMPETITORS =====
    {
        "name": "QGenda",
        "website": "https://www.qgenda.com",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Per Provider",
        "base_price": "$50",
        "price_unit": "per provider/month",
        "product_categories": "Provider Scheduling; Workforce",
        "key_features": "Physician scheduling, On-call management, Time tracking, Analytics",
        "integration_partners": "Epic; Cerner; Kronos",
        "certifications": "HIPAA; SOC2",
        "target_segments": "Health Systems; Hospitals",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "4000+",
        "customer_acquisition_rate": "Strong",
        "key_customers": "Health systems",
        "g2_rating": "4.5",
        "employee_count": "500+",
        "employee_growth_rate": "25% YoY",
        "year_founded": "2006",
        "headquarters": "Atlanta, GA",
        "funding_total": "$200M+",
        "latest_round": "PE Backed",
        "pe_vc_backers": "Francisco Partners",
        "website_traffic": "50K+",
        "social_following": "10K+",
        "recent_launches": "Advanced Analytics",
        "news_mentions": "15",
    },
    {
        "name": "OpenTable for Healthcare (acquired by Kyruus)",
        "website": "https://www.kyruus.com",
        "status": "Active",
        "threat_level": "High",
        "pricing_model": "Enterprise",
        "base_price": "Custom",
        "price_unit": "enterprise pricing",
        "product_categories": "Provider Search; Scheduling; Access",
        "key_features": "Provider matching, Online scheduling, Network optimization",
        "integration_partners": "Epic; Cerner",
        "certifications": "HIPAA; SOC2",
        "target_segments": "Health Systems; Enterprise",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "700+",
        "customer_acquisition_rate": "Strong",
        "key_customers": "Cleveland Clinic; Intermountain",
        "g2_rating": "4.4",
        "employee_count": "500+",
        "employee_growth_rate": "20% YoY",
        "year_founded": "2010",
        "headquarters": "Boston, MA",
        "funding_total": "$150M+",
        "latest_round": "PE Backed",
        "pe_vc_backers": "Francisco Partners",
        "website_traffic": "60K+",
        "social_following": "10K+",
        "recent_launches": "AI matching",
        "news_mentions": "20",
    },
    {
        "name": "NexHealth",
        "website": "https://www.nexhealth.com",
        "status": "Active",
        "threat_level": "High",
        "pricing_model": "Per Location",
        "base_price": "$350",
        "price_unit": "per location/month",
        "product_categories": "Scheduling; Intake; Payments; Communications",
        "key_features": "Online booking, Digital forms, 2-way texting, Payments, Reviews",
        "integration_partners": "Dental and medical PM/EHRs",
        "certifications": "HIPAA; SOC2",
        "target_segments": "Dental; Specialty; Primary Care",
        "customer_size_focus": "Medium (15-50)",
        "geographic_focus": "US National",
        "customer_count": "8000+",
        "customer_acquisition_rate": "Fast growing",
        "key_customers": "Dental and medical practices",
        "g2_rating": "4.7",
        "employee_count": "200+",
        "employee_growth_rate": "80% YoY",
        "year_founded": "2017",
        "headquarters": "San Francisco, CA",
        "funding_total": "$125M+",
        "latest_round": "Series C",
        "pe_vc_backers": "Andreessen; Point72",
        "website_traffic": "100K+",
        "social_following": "10K+",
        "recent_launches": "Unified platform",
        "news_mentions": "25",
    },
    # ===== SPECIALTY-SPECIFIC COMPETITORS =====
    {
        "name": "Weave",
        "website": "https://www.getweave.com",
        "status": "Active",
        "threat_level": "High",
        "pricing_model": "Per Location",
        "base_price": "$399",
        "price_unit": "per location/month",
        "product_categories": "Communications; Payments; Scheduling",
        "key_features": "VoIP phones, Text messaging, Payments, Reviews, Scheduling",
        "integration_partners": "Dental and optical PM systems",
        "certifications": "HIPAA; PCI-DSS",
        "target_segments": "Dental; Optometry; Veterinary",
        "customer_size_focus": "Small (1-15)",
        "geographic_focus": "US National",
        "customer_count": "27000+",
        "customer_acquisition_rate": "High",
        "key_customers": "Dental practices",
        "g2_rating": "4.3",
        "employee_count": "900+",
        "employee_growth_rate": "20% YoY",
        "year_founded": "2011",
        "headquarters": "Lehi, UT",
        "funding_total": "$160M+",
        "latest_round": "Public (NYSE: WEAV)",
        "pe_vc_backers": "Public",
        "website_traffic": "200K+",
        "social_following": "30K+",
        "recent_launches": "Weave Payments",
        "news_mentions": "30",
    },
    {
        "name": "RevenueWell",
        "website": "https://www.revenuewell.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Per Location",
        "base_price": "$299",
        "price_unit": "per location/month",
        "product_categories": "Patient Communications; Marketing; Scheduling",
        "key_features": "Patient reminders, Online scheduling, Reviews, Marketing",
        "integration_partners": "Dental PM systems",
        "certifications": "HIPAA",
        "target_segments": "Dental",
        "customer_size_focus": "Small (1-15)",
        "geographic_focus": "US National",
        "customer_count": "10000+",
        "customer_acquisition_rate": "Strong",
        "key_customers": "Dental practices",
        "g2_rating": "4.4",
        "employee_count": "200+",
        "employee_growth_rate": "15% YoY",
        "year_founded": "2009",
        "headquarters": "Chicago, IL",
        "funding_total": "Acquired",
        "latest_round": "Acquired by Marlin",
        "pe_vc_backers": "Marlin Equity",
        "website_traffic": "50K+",
        "social_following": "5K+",
        "recent_launches": "Marketing automation",
        "news_mentions": "10",
    },
    {
        "name": "Lighthouse 360",
        "website": "https://www.lh360.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Per Location",
        "base_price": "$329",
        "price_unit": "per location/month",
        "product_categories": "Patient Communications; Reminders",
        "key_features": "Automated reminders, Online scheduling, Recall, Reviews",
        "integration_partners": "Dental PM systems",
        "certifications": "HIPAA",
        "target_segments": "Dental",
        "customer_size_focus": "Small (1-15)",
        "geographic_focus": "US National",
        "customer_count": "15000+",
        "customer_acquisition_rate": "Steady",
        "key_customers": "Dental practices",
        "g2_rating": "4.2",
        "employee_count": "150+",
        "employee_growth_rate": "10% YoY",
        "year_founded": "2006",
        "headquarters": "Irvine, CA",
        "funding_total": "Acquired",
        "latest_round": "Acquired by Henry Schein",
        "pe_vc_backers": "Henry Schein",
        "website_traffic": "30K+",
        "social_following": "5K+",
        "recent_launches": "Virtual check-in",
        "news_mentions": "5",
    },
    {
        "name": "Sycle",
        "website": "https://www.sycle.net",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Per Location",
        "base_price": "$250",
        "price_unit": "per location/month",
        "product_categories": "Practice Management; Scheduling",
        "key_features": "Audiology PM, Scheduling, Patient records, Marketing",
        "integration_partners": "Audiology equipment",
        "certifications": "HIPAA",
        "target_segments": "Audiology; Hearing Care",
        "customer_size_focus": "Small (1-15)",
        "geographic_focus": "US National",
        "customer_count": "5000+",
        "customer_acquisition_rate": "Steady",
        "key_customers": "Audiology practices",
        "g2_rating": "4.0",
        "employee_count": "100+",
        "employee_growth_rate": "10% YoY",
        "year_founded": "2001",
        "headquarters": "San Jose, CA",
        "funding_total": "Acquired",
        "latest_round": "Acquired by Demant",
        "pe_vc_backers": "Demant",
        "website_traffic": "20K+",
        "social_following": "2K+",
        "recent_launches": "Cloud migration",
        "news_mentions": "3",
    },
    # ===== PATIENT PAYMENT / FINANCIAL ENGAGEMENT COMPETITORS =====
    {
        "name": "Collectly",
        "website": "https://www.collectly.co",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Percentage",
        "base_price": "3-5%",
        "price_unit": "of collections",
        "product_categories": "Patient Payments; Collections",
        "key_features": "Patient billing, Collections automation, Payment plans, Text-to-pay",
        "integration_partners": "Major PM/EHR systems",
        "certifications": "HIPAA; PCI-DSS",
        "target_segments": "Specialty; Urgent Care",
        "customer_size_focus": "Medium (15-50)",
        "geographic_focus": "US National",
        "customer_count": "500+",
        "customer_acquisition_rate": "Fast growing",
        "key_customers": "Specialty practices",
        "g2_rating": "4.6",
        "employee_count": "50+",
        "employee_growth_rate": "50% YoY",
        "year_founded": "2016",
        "headquarters": "Los Angeles, CA",
        "funding_total": "$20M+",
        "latest_round": "Series A",
        "pe_vc_backers": "Y Combinator",
        "website_traffic": "15K+",
        "social_following": "2K+",
        "recent_launches": "AI collections",
        "news_mentions": "8",
    },
    {
        "name": "VisitPay",
        "website": "https://www.visitpay.com",
        "status": "Acquired",
        "threat_level": "Medium",
        "pricing_model": "Enterprise",
        "base_price": "Custom",
        "price_unit": "enterprise pricing",
        "product_categories": "Patient Payments; Financial Engagement",
        "key_features": "Patient financing, Payment plans, Price transparency, Financial counseling",
        "integration_partners": "Epic; Cerner",
        "certifications": "HIPAA; PCI-DSS",
        "target_segments": "Health Systems; Hospitals",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "100+",
        "customer_acquisition_rate": "Acquired",
        "key_customers": "Health systems",
        "g2_rating": "4.2",
        "employee_count": "Part of Flywire",
        "employee_growth_rate": "Acquired",
        "year_founded": "2010",
        "headquarters": "Salt Lake City, UT",
        "funding_total": "Acquired by Flywire",
        "latest_round": "Acquired",
        "pe_vc_backers": "Flywire",
        "website_traffic": "10K+",
        "social_following": "2K+",
        "recent_launches": "Flywire integration",
        "news_mentions": "10",
    },
    {
        "name": "Flywire Healthcare",
        "website": "https://www.flywire.com/industries/healthcare",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Enterprise",
        "base_price": "Custom",
        "price_unit": "enterprise pricing",
        "product_categories": "Patient Payments; Financing",
        "key_features": "Complex payments, Multi-currency, Payment plans, Financial engagement",
        "integration_partners": "Epic; Cerner; Major ERPs",
        "certifications": "HIPAA; PCI-DSS; SOC2",
        "target_segments": "Health Systems; Academic Medical Centers",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "Global",
        "customer_count": "200+",
        "customer_acquisition_rate": "Growing",
        "key_customers": "Academic medical centers",
        "g2_rating": "4.3",
        "employee_count": "1000+",
        "employee_growth_rate": "30% YoY",
        "year_founded": "2011",
        "headquarters": "Boston, MA",
        "funding_total": "Public",
        "latest_round": "Public (NASDAQ: FLYW)",
        "pe_vc_backers": "Public",
        "website_traffic": "200K+",
        "social_following": "15K+",
        "recent_launches": "Healthcare expansion",
        "news_mentions": "25",
    },
    {
        "name": "AccessOne",
        "website": "https://www.accessonemed.com",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Enterprise",
        "base_price": "Custom",
        "price_unit": "enterprise pricing",
        "product_categories": "Patient Financing; Payments",
        "key_features": "0% financing, Payment plans, Financial assistance, Credit line",
        "integration_partners": "Epic; Cerner",
        "certifications": "HIPAA; PCI-DSS",
        "target_segments": "Health Systems; Hospitals",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "500+",
        "customer_acquisition_rate": "Steady",
        "key_customers": "Health systems",
        "g2_rating": "4.0",
        "employee_count": "200+",
        "employee_growth_rate": "10% YoY",
        "year_founded": "2006",
        "headquarters": "Charlotte, NC",
        "funding_total": "$100M+",
        "latest_round": "PE Backed",
        "pe_vc_backers": "Parthenon Capital",
        "website_traffic": "20K+",
        "social_following": "3K+",
        "recent_launches": "Digital enrollment",
        "news_mentions": "8",
    },
    # ===== ADDITIONAL COMPREHENSIVE COMPETITORS =====
    {
        "name": "Healthgrades",
        "website": "https://www.healthgrades.com",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Subscription",
        "base_price": "$500",
        "price_unit": "per provider/year",
        "product_categories": "Provider Reviews; Marketing; Scheduling",
        "key_features": "Provider profiles, Patient reviews, Online booking, Marketing",
        "integration_partners": "Limited",
        "certifications": "HIPAA",
        "target_segments": "Hospitals; Practices",
        "customer_size_focus": "All Sizes",
        "geographic_focus": "US National",
        "customer_count": "1M+ providers listed",
        "customer_acquisition_rate": "Established",
        "key_customers": "Hospitals and practices",
        "g2_rating": "3.5",
        "employee_count": "300+",
        "employee_growth_rate": "5% YoY",
        "year_founded": "1998",
        "headquarters": "Denver, CO",
        "funding_total": "Acquired",
        "latest_round": "Acquired by Red Ventures",
        "pe_vc_backers": "Red Ventures",
        "website_traffic": "10M+",
        "social_following": "50K+",
        "recent_launches": "Care journeys",
        "news_mentions": "20",
    },
    {
        "name": "Vitals",
        "website": "https://www.vitals.com",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Advertising",
        "base_price": "Variable",
        "price_unit": "per lead",
        "product_categories": "Provider Search; Reviews",
        "key_features": "Provider search, Patient reviews, Insurance lookup",
        "integration_partners": "Limited",
        "certifications": "N/A",
        "target_segments": "Consumers; Providers",
        "customer_size_focus": "N/A",
        "geographic_focus": "US National",
        "customer_count": "Public directory",
        "customer_acquisition_rate": "Established",
        "key_customers": "N/A",
        "g2_rating": "3.0",
        "employee_count": "50+",
        "employee_growth_rate": "Flat",
        "year_founded": "2008",
        "headquarters": "Lyndhurst, NJ",
        "funding_total": "Private",
        "latest_round": "Private",
        "pe_vc_backers": "Private",
        "website_traffic": "3M+",
        "social_following": "10K+",
        "recent_launches": "Mobile app",
        "news_mentions": "5",
    },
    {
        "name": "Doctor.com (Press Ganey)",
        "website": "https://www.doctor.com",
        "status": "Acquired",
        "threat_level": "Medium",
        "pricing_model": "Enterprise",
        "base_price": "Custom",
        "price_unit": "enterprise pricing",
        "product_categories": "Reputation; Listings; Patient Acquisition",
        "key_features": "Reputation management, Provider listings, Patient reviews",
        "integration_partners": "Major EHRs",
        "certifications": "HIPAA",
        "target_segments": "Health Systems",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "300+",
        "customer_acquisition_rate": "Acquired",
        "key_customers": "Health systems",
        "g2_rating": "4.0",
        "employee_count": "Part of Press Ganey",
        "employee_growth_rate": "Acquired",
        "year_founded": "2012",
        "headquarters": "New York, NY",
        "funding_total": "Acquired by Press Ganey",
        "latest_round": "Acquired",
        "pe_vc_backers": "Press Ganey",
        "website_traffic": "500K+",
        "social_following": "5K+",
        "recent_launches": "Integration with PG",
        "news_mentions": "10",
    },
    {
        "name": "Podium",
        "website": "https://www.podium.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Per Location",
        "base_price": "$399",
        "price_unit": "per location/month",
        "product_categories": "Reviews; Messaging; Payments",
        "key_features": "Review management, Text messaging, Webchat, Payments",
        "integration_partners": "Various industry systems",
        "certifications": "HIPAA (healthcare tier)",
        "target_segments": "Multi-industry; Healthcare",
        "customer_size_focus": "Small (1-15)",
        "geographic_focus": "US National",
        "customer_count": "100000+",
        "customer_acquisition_rate": "Very High",
        "key_customers": "Multi-industry",
        "g2_rating": "4.5",
        "employee_count": "1500+",
        "employee_growth_rate": "30% YoY",
        "year_founded": "2014",
        "headquarters": "Lehi, UT",
        "funding_total": "$200M+",
        "latest_round": "Series D",
        "pe_vc_backers": "Y Combinator; Accel",
        "website_traffic": "1M+",
        "social_following": "50K+",
        "recent_launches": "AI messaging",
        "news_mentions": "30",
    },
    {
        "name": "Birdeye",
        "website": "https://birdeye.com",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Per Location",
        "base_price": "$299",
        "price_unit": "per location/month",
        "product_categories": "Reviews; Reputation; Surveys",
        "key_features": "Review generation, Reputation management, Surveys, Listings",
        "integration_partners": "Various PM systems",
        "certifications": "HIPAA (healthcare tier)",
        "target_segments": "Multi-industry; Healthcare",
        "customer_size_focus": "Small (1-15)",
        "geographic_focus": "US National",
        "customer_count": "100000+",
        "customer_acquisition_rate": "High",
        "key_customers": "Multi-industry",
        "g2_rating": "4.7",
        "employee_count": "1000+",
        "employee_growth_rate": "40% YoY",
        "year_founded": "2012",
        "headquarters": "Palo Alto, CA",
        "funding_total": "$60M+",
        "latest_round": "Series C",
        "pe_vc_backers": "Accel; Salesforce",
        "website_traffic": "500K+",
        "social_following": "30K+",
        "recent_launches": "AI insights",
        "news_mentions": "20",
    },
]
