# Additional 50 competitors data - Part 1 (25 competitors)
# Organized by Certify Health competitive categories

ADDITIONAL_COMPETITORS_PART1 = [
    # ===== PATIENT INTAKE / DIGITAL CHECK-IN COMPETITORS =====
    {
        "name": "Zocdoc",
        "website": "https://www.zocdoc.com",
        "status": "Active",
        "threat_level": "High",
        "pricing_model": "Per Booking",
        "base_price": "$35",
        "price_unit": "per new patient booking",
        "product_categories": "Patient Scheduling; Intake; Reviews",
        "key_features": "Online booking, Patient reviews, Digital intake forms, Insurance verification",
        "integration_partners": "Epic; Cerner; athena; Allscripts",
        "certifications": "HIPAA; SOC2",
        "target_segments": "Multi-specialty; Dental; Primary Care",
        "customer_size_focus": "All Sizes",
        "geographic_focus": "US National",
        "customer_count": "12000+",
        "customer_acquisition_rate": "High",
        "key_customers": "Mount Sinai; NYU Langone",
        "g2_rating": "4.4",
        "employee_count": "600+",
        "employee_growth_rate": "10% YoY",
        "year_founded": "2007",
        "headquarters": "New York, NY",
        "funding_total": "$375M+",
        "latest_round": "Series D",
        "pe_vc_backers": "Founders Fund; Khosla; Atomico",
        "website_traffic": "5M+",
        "social_following": "100K+",
        "recent_launches": "Zocdoc Video Service",
        "news_mentions": "50",
    },
    {
        "name": "Doctolib",
        "website": "https://www.doctolib.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Subscription",
        "base_price": "€129",
        "price_unit": "per month",
        "product_categories": "Scheduling; Intake; Telehealth",
        "key_features": "Online booking, Patient records, Video consultations, Automated reminders",
        "integration_partners": "European EHR systems",
        "certifications": "HIPAA equivalent (EU); GDPR",
        "target_segments": "Primary Care; Hospitals",
        "customer_size_focus": "All Sizes",
        "geographic_focus": "Europe (France, Germany, Italy)",
        "customer_count": "340000+",
        "customer_acquisition_rate": "Very High",
        "key_customers": "European hospitals",
        "g2_rating": "4.2",
        "employee_count": "2800+",
        "employee_growth_rate": "30% YoY",
        "year_founded": "2013",
        "headquarters": "Paris, France",
        "funding_total": "$500M+",
        "latest_round": "Series F",
        "pe_vc_backers": "Eurazeo; Bpifrance",
        "website_traffic": "10M+",
        "social_following": "200K+",
        "recent_launches": "AI scheduling assistant",
        "news_mentions": "100",
    },
    {
        "name": "Intakeq",
        "website": "https://intakeq.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Subscription",
        "base_price": "$49.90",
        "price_unit": "per month",
        "product_categories": "Intake Forms; Patient Portal; Scheduling",
        "key_features": "Custom intake forms, E-signatures, Appointment booking, Secure messaging",
        "integration_partners": "Stripe; Google Calendar; Zoom",
        "certifications": "HIPAA",
        "target_segments": "Mental Health; Allied Health; Wellness",
        "customer_size_focus": "Small (1-15)",
        "geographic_focus": "US; Canada; UK",
        "customer_count": "15000+",
        "customer_acquisition_rate": "Growing",
        "key_customers": "Mental health practices",
        "g2_rating": "4.7",
        "employee_count": "30+",
        "employee_growth_rate": "20% YoY",
        "year_founded": "2015",
        "headquarters": "Toronto, Canada",
        "funding_total": "Bootstrapped",
        "latest_round": "N/A",
        "pe_vc_backers": "N/A",
        "website_traffic": "100K+",
        "social_following": "5K+",
        "recent_launches": "Telehealth integration",
        "news_mentions": "5",
    },
    {
        "name": "FormDr",
        "website": "https://www.formdr.com",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Subscription",
        "base_price": "$49",
        "price_unit": "per month",
        "product_categories": "Patient Intake Forms; E-signatures",
        "key_features": "HIPAA forms, Digital signatures, Form templates, Auto-populate",
        "integration_partners": "Various PM systems",
        "certifications": "HIPAA",
        "target_segments": "Small Practices; Chiropractors",
        "customer_size_focus": "Small (1-15)",
        "geographic_focus": "US National",
        "customer_count": "5000+",
        "customer_acquisition_rate": "Steady",
        "key_customers": "Independent practices",
        "g2_rating": "4.5",
        "employee_count": "20+",
        "employee_growth_rate": "10% YoY",
        "year_founded": "2013",
        "headquarters": "Denver, CO",
        "funding_total": "Private",
        "latest_round": "Private",
        "pe_vc_backers": "Private",
        "website_traffic": "20K+",
        "social_following": "2K+",
        "recent_launches": "Mobile forms",
        "news_mentions": "2",
    },
    {
        "name": "Jotform Health",
        "website": "https://www.jotform.com/health",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Freemium",
        "base_price": "$0",
        "price_unit": "free tier available",
        "product_categories": "Intake Forms; Surveys; Telehealth",
        "key_features": "HIPAA-compliant forms, Telehealth integration, E-signatures, Templates",
        "integration_partners": "Zoom; Google; Salesforce",
        "certifications": "HIPAA BAA available",
        "target_segments": "Healthcare; Wellness; Mental Health",
        "customer_size_focus": "All Sizes",
        "geographic_focus": "Global",
        "customer_count": "100000+ healthcare users",
        "customer_acquisition_rate": "Very High",
        "key_customers": "Various healthcare orgs",
        "g2_rating": "4.6",
        "employee_count": "600+",
        "employee_growth_rate": "20% YoY",
        "year_founded": "2006",
        "headquarters": "San Francisco, CA",
        "funding_total": "Bootstrapped",
        "latest_round": "N/A",
        "pe_vc_backers": "N/A",
        "website_traffic": "10M+",
        "social_following": "100K+",
        "recent_launches": "Jotform Health Templates",
        "news_mentions": "15",
    },
    # ===== REVENUE CYCLE MANAGEMENT (RCM) COMPETITORS =====
    {
        "name": "Availity",
        "website": "https://www.availity.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Enterprise",
        "base_price": "Custom",
        "price_unit": "enterprise pricing",
        "product_categories": "RCM; Eligibility; Claims",
        "key_features": "Real-time eligibility, Claims management, Payer connectivity, Prior auth",
        "integration_partners": "Major payers and EHRs",
        "certifications": "HIPAA; SOC2",
        "target_segments": "Health Systems; Payers",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "2M+ providers",
        "customer_acquisition_rate": "Strong",
        "key_customers": "Major health systems",
        "g2_rating": "4.0",
        "employee_count": "1000+",
        "employee_growth_rate": "10% YoY",
        "year_founded": "2001",
        "headquarters": "Jacksonville, FL",
        "funding_total": "Private",
        "latest_round": "Private",
        "pe_vc_backers": "BCBS companies",
        "website_traffic": "200K+",
        "social_following": "10K+",
        "recent_launches": "AI-powered prior auth",
        "news_mentions": "20",
    },
    {
        "name": "Change Healthcare",
        "website": "https://www.changehealthcare.com",
        "status": "Acquired",
        "threat_level": "High",
        "pricing_model": "Transaction",
        "base_price": "Variable",
        "price_unit": "per transaction",
        "product_categories": "RCM; Claims; Analytics; Payments",
        "key_features": "Claims processing, Payment integrity, Analytics, Revenue cycle",
        "integration_partners": "Wide network",
        "certifications": "HIPAA; SOC2; HITRUST",
        "target_segments": "Health Systems; Payers; Pharmacies",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "Millions of transactions",
        "customer_acquisition_rate": "Acquired by Optum",
        "key_customers": "Major health systems",
        "g2_rating": "3.8",
        "employee_count": "15000+",
        "employee_growth_rate": "Acquired",
        "year_founded": "2007",
        "headquarters": "Nashville, TN",
        "funding_total": "$1B+",
        "latest_round": "Acquired by UHG/Optum",
        "pe_vc_backers": "UnitedHealth Group",
        "website_traffic": "500K+",
        "social_following": "50K+",
        "recent_launches": "AI claims intelligence",
        "news_mentions": "200",
    },
    {
        "name": "R1 RCM",
        "website": "https://www.r1rcm.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Enterprise",
        "base_price": "Custom",
        "price_unit": "enterprise pricing",
        "product_categories": "RCM; Patient Access; Analytics",
        "key_features": "End-to-end RCM, Patient access, Physician advisory, Analytics",
        "integration_partners": "Major EHRs",
        "certifications": "HIPAA; SOC2",
        "target_segments": "Health Systems; Hospitals",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "3000+",
        "customer_acquisition_rate": "Strong",
        "key_customers": "Major health systems",
        "g2_rating": "3.9",
        "employee_count": "28000+",
        "employee_growth_rate": "15% YoY",
        "year_founded": "2003",
        "headquarters": "Chicago, IL",
        "funding_total": "Public",
        "latest_round": "Public (NASDAQ: RCM)",
        "pe_vc_backers": "Public",
        "website_traffic": "100K+",
        "social_following": "20K+",
        "recent_launches": "AI-powered denials",
        "news_mentions": "40",
    },
    {
        "name": "Ensemble Health Partners",
        "website": "https://www.ensemblehp.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Enterprise",
        "base_price": "Custom",
        "price_unit": "enterprise pricing",
        "product_categories": "RCM; Patient Access; Coding",
        "key_features": "Revenue cycle outsourcing, Patient access, Coding services",
        "integration_partners": "Major EHRs",
        "certifications": "HIPAA",
        "target_segments": "Health Systems; Hospitals",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "350+",
        "customer_acquisition_rate": "Growing",
        "key_customers": "Health systems",
        "g2_rating": "4.0",
        "employee_count": "5000+",
        "employee_growth_rate": "20% YoY",
        "year_founded": "2014",
        "headquarters": "Cincinnati, OH",
        "funding_total": "$500M+",
        "latest_round": "PE Backed",
        "pe_vc_backers": "Golden Gate Capital",
        "website_traffic": "50K+",
        "social_following": "10K+",
        "recent_launches": "AI revenue optimization",
        "news_mentions": "15",
    },
    {
        "name": "Omega Healthcare",
        "website": "https://www.omegahms.com",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Enterprise",
        "base_price": "Custom",
        "price_unit": "enterprise pricing",
        "product_categories": "RCM; Coding; Analytics",
        "key_features": "Medical coding, Claims processing, Analytics, RCM outsourcing",
        "integration_partners": "Major EHRs",
        "certifications": "HIPAA; SOC2",
        "target_segments": "Health Systems; Billing Companies",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "300+",
        "customer_acquisition_rate": "Steady",
        "key_customers": "Healthcare organizations",
        "g2_rating": "3.8",
        "employee_count": "23000+",
        "employee_growth_rate": "10% YoY",
        "year_founded": "2003",
        "headquarters": "Bangalore, India",
        "funding_total": "Private",
        "latest_round": "Private",
        "pe_vc_backers": "Private",
        "website_traffic": "30K+",
        "social_following": "15K+",
        "recent_launches": "AI coding",
        "news_mentions": "10",
    },
    # ===== PATIENT ENGAGEMENT COMPETITORS =====
    {
        "name": "Luma Health",
        "website": "https://www.lumahealth.io",
        "status": "Active",
        "threat_level": "High",
        "pricing_model": "Per Location",
        "base_price": "$500",
        "price_unit": "per location/month",
        "product_categories": "Patient Engagement; Scheduling; Intake",
        "key_features": "Smart scheduling, Waitlist, Referral management, Patient communications",
        "integration_partners": "Epic; Cerner; athena; Allscripts",
        "certifications": "HIPAA; SOC2",
        "target_segments": "Health Systems; Specialty",
        "customer_size_focus": "Large (50+)",
        "geographic_focus": "US National",
        "customer_count": "700+",
        "customer_acquisition_rate": "Fast growing",
        "key_customers": "Scripps; Stanford",
        "g2_rating": "4.8",
        "employee_count": "250+",
        "employee_growth_rate": "40% YoY",
        "year_founded": "2015",
        "headquarters": "San Francisco, CA",
        "funding_total": "$160M+",
        "latest_round": "Series C",
        "pe_vc_backers": "U.S. Venture Partners",
        "website_traffic": "50K+",
        "social_following": "10K+",
        "recent_launches": "AI scheduling",
        "news_mentions": "25",
    },
    {
        "name": "Cedar",
        "website": "https://www.cedar.com",
        "status": "Active",
        "threat_level": "High",
        "pricing_model": "Enterprise",
        "base_price": "Custom",
        "price_unit": "enterprise pricing",
        "product_categories": "Patient Payments; Engagement; RCM",
        "key_features": "Patient billing, Payment plans, Cost estimates, Digital experience",
        "integration_partners": "Epic; Cerner",
        "certifications": "HIPAA; SOC2; PCI-DSS",
        "target_segments": "Health Systems; Hospitals",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "55+",
        "customer_acquisition_rate": "Enterprise sales",
        "key_customers": "Yale; Summit Health",
        "g2_rating": "4.3",
        "employee_count": "400+",
        "employee_growth_rate": "50% YoY",
        "year_founded": "2016",
        "headquarters": "New York, NY",
        "funding_total": "$350M+",
        "latest_round": "Series D",
        "pe_vc_backers": "Tiger Global; Andreessen",
        "website_traffic": "30K+",
        "social_following": "5K+",
        "recent_launches": "Cedar Pay",
        "news_mentions": "30",
    },
    {
        "name": "PatientPoint",
        "website": "https://www.patientpoint.com",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Enterprise",
        "base_price": "Custom",
        "price_unit": "enterprise pricing",
        "product_categories": "Patient Engagement; Education; Marketing",
        "key_features": "Waiting room engagement, Patient education, Digital signage",
        "integration_partners": "Limited",
        "certifications": "HIPAA",
        "target_segments": "Pharma; Health Systems",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "35000+",
        "customer_acquisition_rate": "Steady",
        "key_customers": "Health systems",
        "g2_rating": "3.8",
        "employee_count": "500+",
        "employee_growth_rate": "10% YoY",
        "year_founded": "2009",
        "headquarters": "Cincinnati, OH",
        "funding_total": "$100M+",
        "latest_round": "PE Backed",
        "pe_vc_backers": "Searchlight Capital",
        "website_traffic": "50K+",
        "social_following": "5K+",
        "recent_launches": "Digital waiting room",
        "news_mentions": "10",
    },
    {
        "name": "Relatient",
        "website": "https://www.relatient.com",
        "status": "Active",
        "threat_level": "High",
        "pricing_model": "Per Location",
        "base_price": "$350",
        "price_unit": "per location/month",
        "product_categories": "Patient Engagement; Scheduling; Intake",
        "key_features": "Self-scheduling, Digital intake, Reminders, Reputation management",
        "integration_partners": "Epic; Cerner; athena",
        "certifications": "HIPAA; SOC2",
        "target_segments": "Health Systems; Large Practices",
        "customer_size_focus": "Large (50+)",
        "geographic_focus": "US National",
        "customer_count": "600+",
        "customer_acquisition_rate": "Growing",
        "key_customers": "Health systems",
        "g2_rating": "4.4",
        "employee_count": "250+",
        "employee_growth_rate": "25% YoY",
        "year_founded": "2014",
        "headquarters": "Franklin, TN",
        "funding_total": "$60M+",
        "latest_round": "Series C",
        "pe_vc_backers": "Axiom Equity",
        "website_traffic": "30K+",
        "social_following": "5K+",
        "recent_launches": "AI scheduling",
        "news_mentions": "12",
    },
    {
        "name": "Stericycle Communication Solutions",
        "website": "https://www.stericyclecommunications.com",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Enterprise",
        "base_price": "Custom",
        "price_unit": "enterprise pricing",
        "product_categories": "Patient Communication; Call Center",
        "key_features": "Patient call center, Appointment reminders, After-hours support",
        "integration_partners": "Major EHRs",
        "certifications": "HIPAA",
        "target_segments": "Health Systems; Hospitals",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "1000+",
        "customer_acquisition_rate": "Steady",
        "key_customers": "Health systems",
        "g2_rating": "3.5",
        "employee_count": "3000+",
        "employee_growth_rate": "5% YoY",
        "year_founded": "1989",
        "headquarters": "Lake Forest, IL",
        "funding_total": "Public",
        "latest_round": "Public (NASDAQ: SRCL)",
        "pe_vc_backers": "Public",
        "website_traffic": "20K+",
        "social_following": "10K+",
        "recent_launches": "Digital communications",
        "news_mentions": "5",
    },
    # ===== BIOMETRIC / IDENTITY VERIFICATION COMPETITORS =====
    {
        "name": "Imprivata",
        "website": "https://www.imprivata.com",
        "status": "Active",
        "threat_level": "High",
        "pricing_model": "Per User",
        "base_price": "$10",
        "price_unit": "per user/month",
        "product_categories": "Identity; Authentication; SSO",
        "key_features": "Single sign-on, Biometric authentication, EPCS compliance, Patient ID",
        "integration_partners": "Epic; Cerner; All major EHRs",
        "certifications": "HIPAA; SOC2; HITRUST",
        "target_segments": "Health Systems; Hospitals",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "Global",
        "customer_count": "2000+",
        "customer_acquisition_rate": "Strong",
        "key_customers": "Major health systems",
        "g2_rating": "4.5",
        "employee_count": "600+",
        "employee_growth_rate": "15% YoY",
        "year_founded": "2002",
        "headquarters": "Waltham, MA",
        "funding_total": "$200M+",
        "latest_round": "PE Owned",
        "pe_vc_backers": "Thoma Bravo",
        "website_traffic": "100K+",
        "social_following": "15K+",
        "recent_launches": "Patient Identity verification",
        "news_mentions": "25",
    },
    {
        "name": "RightPatient",
        "website": "https://www.rightpatient.com",
        "status": "Active",
        "threat_level": "High",
        "pricing_model": "Per Transaction",
        "base_price": "$0.25",
        "price_unit": "per verification",
        "product_categories": "Patient ID; Biometrics; Identity",
        "key_features": "Photo-based patient ID, Biometric verification, Fraud prevention",
        "integration_partners": "Major EHRs",
        "certifications": "HIPAA",
        "target_segments": "Health Systems; Hospitals",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "200+",
        "customer_acquisition_rate": "Growing",
        "key_customers": "Health systems",
        "g2_rating": "4.2",
        "employee_count": "50+",
        "employee_growth_rate": "20% YoY",
        "year_founded": "2010",
        "headquarters": "Memphis, TN",
        "funding_total": "$20M+",
        "latest_round": "Series B",
        "pe_vc_backers": "VC Backed",
        "website_traffic": "10K+",
        "social_following": "2K+",
        "recent_launches": "Touchless patient ID",
        "news_mentions": "8",
    },
    {
        "name": "CLEAR Health Pass",
        "website": "https://www.clearme.com/healthpass",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Subscription",
        "base_price": "$189",
        "price_unit": "per year",
        "product_categories": "Identity; Health Verification",
        "key_features": "Biometric identity, Health verification, Touchless access",
        "integration_partners": "Various health systems",
        "certifications": "SOC2",
        "target_segments": "Employers; Venues; Healthcare",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "15M+ members",
        "customer_acquisition_rate": "High",
        "key_customers": "Airports; Stadiums; Health systems",
        "g2_rating": "4.0",
        "employee_count": "800+",
        "employee_growth_rate": "20% YoY",
        "year_founded": "2010",
        "headquarters": "New York, NY",
        "funding_total": "$300M+",
        "latest_round": "Public (NYSE: YOU)",
        "pe_vc_backers": "Public",
        "website_traffic": "1M+",
        "social_following": "50K+",
        "recent_launches": "Healthcare partnerships",
        "news_mentions": "50",
    },
    {
        "name": "Verato",
        "website": "https://www.verato.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Enterprise",
        "base_price": "Custom",
        "price_unit": "enterprise pricing",
        "product_categories": "Identity; Master Patient Index",
        "key_features": "Patient matching, Identity resolution, Data quality, Referential DB",
        "integration_partners": "Major EHRs",
        "certifications": "HIPAA; HITRUST",
        "target_segments": "Health Systems; Payers",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "100+",
        "customer_acquisition_rate": "Growing",
        "key_customers": "Health systems",
        "g2_rating": "4.3",
        "employee_count": "200+",
        "employee_growth_rate": "25% YoY",
        "year_founded": "2006",
        "headquarters": "McLean, VA",
        "funding_total": "$100M+",
        "latest_round": "Series C",
        "pe_vc_backers": "Mercury Capital",
        "website_traffic": "20K+",
        "social_following": "5K+",
        "recent_launches": "Cloud-native EMPI",
        "news_mentions": "15",
    },
    {
        "name": "Experian Patient Identity",
        "website": "https://www.experian.com/healthcare/patient-identity",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Enterprise",
        "base_price": "Custom",
        "price_unit": "enterprise pricing",
        "product_categories": "Identity; Patient Matching; Data Quality",
        "key_features": "Universal patient identifier, Identity resolution, Data quality",
        "integration_partners": "Major EHRs",
        "certifications": "HIPAA; SOC2",
        "target_segments": "Health Systems; Enterprise",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "5000+",
        "customer_acquisition_rate": "Enterprise sales",
        "key_customers": "Major health systems",
        "g2_rating": "4.0",
        "employee_count": "Part of Experian",
        "employee_growth_rate": "Part of Experian",
        "year_founded": "2015",
        "headquarters": "Franklin, TN",
        "funding_total": "Public company division",
        "latest_round": "N/A",
        "pe_vc_backers": "Experian (Public)",
        "website_traffic": "100K+ (healthcare)",
        "social_following": "10K+",
        "recent_launches": "Universal patient ID",
        "news_mentions": "15",
    },
    # ===== TELEHEALTH / VIRTUAL CARE COMPETITORS =====
    {
        "name": "Teladoc Health",
        "website": "https://www.teladoc.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Per Visit",
        "base_price": "$89",
        "price_unit": "per visit",
        "product_categories": "Telehealth; Virtual Care; Mental Health",
        "key_features": "Video visits, Chronic care, Mental health, Primary care",
        "integration_partners": "Major EHRs; Health plans",
        "certifications": "HIPAA; SOC2",
        "target_segments": "Health Plans; Employers; Health Systems",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "Global",
        "customer_count": "80M+ members",
        "customer_acquisition_rate": "High",
        "key_customers": "Major health plans",
        "g2_rating": "3.8",
        "employee_count": "5000+",
        "employee_growth_rate": "10% YoY",
        "year_founded": "2002",
        "headquarters": "Purchase, NY",
        "funding_total": "Public",
        "latest_round": "Public (NYSE: TDOC)",
        "pe_vc_backers": "Public",
        "website_traffic": "5M+",
        "social_following": "100K+",
        "recent_launches": "AI clinical decision",
        "news_mentions": "200",
    },
    {
        "name": "Amwell",
        "website": "https://www.amwell.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Enterprise",
        "base_price": "Custom",
        "price_unit": "enterprise pricing",
        "product_categories": "Telehealth; Virtual Care Platform",
        "key_features": "White-label telehealth, Provider network, Care coordination",
        "integration_partners": "Major EHRs",
        "certifications": "HIPAA; SOC2",
        "target_segments": "Health Systems; Health Plans",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "2000+",
        "customer_acquisition_rate": "Growing",
        "key_customers": "Major health systems",
        "g2_rating": "3.5",
        "employee_count": "800+",
        "employee_growth_rate": "5% YoY",
        "year_founded": "2006",
        "headquarters": "Boston, MA",
        "funding_total": "Public",
        "latest_round": "Public (NYSE: AMWL)",
        "pe_vc_backers": "Public",
        "website_traffic": "500K+",
        "social_following": "20K+",
        "recent_launches": "Converge platform",
        "news_mentions": "50",
    },
    {
        "name": "Doxy.me",
        "website": "https://doxy.me",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Freemium",
        "base_price": "$0",
        "price_unit": "free basic tier",
        "product_categories": "Telehealth; Video Visits",
        "key_features": "Simple video visits, No downloads, HIPAA compliant, Waiting room",
        "integration_partners": "Limited",
        "certifications": "HIPAA BAA",
        "target_segments": "Solo Practitioners; Small Practices",
        "customer_size_focus": "Solo",
        "geographic_focus": "Global",
        "customer_count": "1M+ providers",
        "customer_acquisition_rate": "Very High",
        "key_customers": "Individual practitioners",
        "g2_rating": "4.5",
        "employee_count": "50+",
        "employee_growth_rate": "30% YoY",
        "year_founded": "2013",
        "headquarters": "Rochester, NY",
        "funding_total": "$10M+",
        "latest_round": "Seed",
        "pe_vc_backers": "VC Backed",
        "website_traffic": "5M+",
        "social_following": "20K+",
        "recent_launches": "HD video",
        "news_mentions": "20",
    },
    {
        "name": "VSee",
        "website": "https://vsee.com",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Per Provider",
        "base_price": "$49",
        "price_unit": "per provider/month",
        "product_categories": "Telehealth; Virtual Clinic",
        "key_features": "Video visits, Virtual waiting room, E-prescribe, EHR integration",
        "integration_partners": "Multiple EHRs",
        "certifications": "HIPAA",
        "target_segments": "Specialty; Mental Health; Primary Care",
        "customer_size_focus": "Small (1-15)",
        "geographic_focus": "US National",
        "customer_count": "10000+",
        "customer_acquisition_rate": "Growing",
        "key_customers": "Specialty practices",
        "g2_rating": "4.2",
        "employee_count": "50+",
        "employee_growth_rate": "15% YoY",
        "year_founded": "2008",
        "headquarters": "Sunnyvale, CA",
        "funding_total": "$10M+",
        "latest_round": "Series A",
        "pe_vc_backers": "VC Backed",
        "website_traffic": "100K+",
        "social_following": "5K+",
        "recent_launches": "Virtual clinic platform",
        "news_mentions": "8",
    },
    {
        "name": "eVisit",
        "website": "https://evisit.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Per Provider",
        "base_price": "$200",
        "price_unit": "per provider/month",
        "product_categories": "Telehealth; Virtual Care",
        "key_features": "Enterprise telehealth, Virtual waiting room, Intake, Video visits",
        "integration_partners": "Major EHRs",
        "certifications": "HIPAA; SOC2",
        "target_segments": "Health Systems; Large Practices",
        "customer_size_focus": "Large (50+)",
        "geographic_focus": "US National",
        "customer_count": "500+",
        "customer_acquisition_rate": "Growing",
        "key_customers": "Health systems",
        "g2_rating": "4.4",
        "employee_count": "150+",
        "employee_growth_rate": "30% YoY",
        "year_founded": "2014",
        "headquarters": "Mesa, AZ",
        "funding_total": "$45M+",
        "latest_round": "Series B",
        "pe_vc_backers": "Goldman Sachs",
        "website_traffic": "30K+",
        "social_following": "5K+",
        "recent_launches": "Enterprise platform",
        "news_mentions": "10",
    },
]
