"""
Certify Intel - Seed Database
Populates the database with initial competitor data from the existing Excel.
"""
import sys
sys.path.insert(0, '.')

from datetime import datetime
from sqlalchemy.orm import Session
from main import Competitor, SessionLocal, engine, Base

# Import additional competitors
from additional_competitors_part1 import ADDITIONAL_COMPETITORS_PART1
from additional_competitors_part2 import ADDITIONAL_COMPETITORS_PART2

# Create tables
Base.metadata.create_all(bind=engine)

# Initial competitor data (same as Excel MWP)
COMPETITORS = [
    {
        "name": "Phreesia",
        "website": "https://www.phreesia.com",
        "status": "Active",
        "threat_level": "High",
        "pricing_model": "Per Visit",
        "base_price": "$3.00",
        "price_unit": "per visit",
        "product_categories": "Intake; Payments; Scheduling",
        "key_features": "Digital intake, Eligibility verification, Patient payments, Appointment reminders",
        "integration_partners": "Epic; Cerner; Allscripts; athenahealth",
        "certifications": "HIPAA; SOC2; HITRUST",
        "target_segments": "Health Systems; Large Practices",
        "customer_size_focus": "Large (50+)",
        "geographic_focus": "US National",
        "customer_count": "3000+",
        "customer_acquisition_rate": "50+ new logos/year",
        "key_customers": "Listed on website",
        "g2_rating": "4.5",
        "employee_count": "1500+",
        "employee_growth_rate": "15% YoY",
        "year_founded": "2005",
        "headquarters": "Raleigh, NC",
        "funding_total": "$300M+",
        "latest_round": "Public (NYSE: PHR)",
        "pe_vc_backers": "Public",
        "website_traffic": "500K+",
        "social_following": "50K+",
        "recent_launches": "AI-powered intake (2024)",
        "news_mentions": "25",
    },
    {
        "name": "Clearwave",
        "website": "https://www.clearwaveinc.com",
        "status": "Active",
        "threat_level": "High",
        "pricing_model": "Per Provider",
        "base_price": "$200",
        "price_unit": "per provider/month",
        "product_categories": "Intake; Eligibility; Payments",
        "key_features": "Patient self-service, Insurance verification, Co-pay collection, Check-in kiosks",
        "integration_partners": "Multiple EHR vendors",
        "certifications": "HIPAA",
        "target_segments": "Specialty Practices; Ambulatory",
        "customer_size_focus": "Medium (15-50)",
        "geographic_focus": "US National",
        "customer_count": "500+",
        "customer_acquisition_rate": "Monthly announcements",
        "key_customers": "Posted on LinkedIn",
        "g2_rating": "4.2",
        "employee_count": "200+",
        "employee_growth_rate": "20% YoY",
        "year_founded": "2003",
        "headquarters": "Atlanta, GA",
        "funding_total": "$50M+",
        "latest_round": "Series C",
        "pe_vc_backers": "Private equity backed",
        "website_traffic": "50K+",
        "social_following": "5K+",
        "recent_launches": "Clearwave AI launch",
        "news_mentions": "15",
    },
    {
        "name": "Epion Health",
        "website": "https://epionhealth.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Per Location",
        "base_price": "Unknown",
        "price_unit": "per month",
        "product_categories": "Intake; Check-in",
        "key_features": "Patient check-in, Digital forms, Wait time management",
        "integration_partners": "Major EHR vendors",
        "certifications": "HIPAA",
        "target_segments": "Health Systems; Enterprise",
        "customer_size_focus": "Large (50+)",
        "geographic_focus": "US National",
        "customer_count": "300+",
        "customer_acquisition_rate": "Unknown",
        "key_customers": "Health systems",
        "g2_rating": "4.0",
        "employee_count": "300+",
        "employee_growth_rate": "Acquired",
        "year_founded": "2011",
        "headquarters": "Acquired by Kyruus",
        "funding_total": "$40M",
        "latest_round": "Acquisition",
        "pe_vc_backers": "Kyruus",
        "website_traffic": "25K+",
        "social_following": "5K",
        "recent_launches": "Kyruus integration",
        "news_mentions": "5",
    },
    {
        "name": "AdvancedMD",
        "website": "https://www.advancedmd.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Per Provider",
        "base_price": "$400",
        "price_unit": "per provider/month",
        "product_categories": "PM; EHR; Intake; RCM",
        "key_features": "Full practice management, EHR, Billing, Patient portal",
        "integration_partners": "Own EHR ecosystem",
        "certifications": "HIPAA; SOC2",
        "target_segments": "Independent Practices",
        "customer_size_focus": "Medium (15-50)",
        "geographic_focus": "US National",
        "customer_count": "40000+",
        "customer_acquisition_rate": "Strong",
        "key_customers": "Many case studies",
        "g2_rating": "4.3",
        "employee_count": "800+",
        "employee_growth_rate": "10% YoY",
        "year_founded": "1999",
        "headquarters": "Salt Lake City, UT",
        "funding_total": "$100M+",
        "latest_round": "PE Owned",
        "pe_vc_backers": "Global Payments",
        "website_traffic": "100K+",
        "social_following": "25K+",
        "recent_launches": "Telehealth updates",
        "news_mentions": "20",
    },
    {
        "name": "Kareo (Tebra)",
        "website": "https://www.kareo.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Tiered",
        "base_price": "$150",
        "price_unit": "starting price",
        "product_categories": "PM; EHR; Billing",
        "key_features": "Practice management, Billing, EHR, Patient engagement",
        "integration_partners": "Many third-party integrations",
        "certifications": "HIPAA",
        "target_segments": "Independent Practices",
        "customer_size_focus": "Small (1-15)",
        "geographic_focus": "US National",
        "customer_count": "75000+",
        "customer_acquisition_rate": "High volume",
        "key_customers": "Case studies available",
        "g2_rating": "4.1",
        "employee_count": "1000+",
        "employee_growth_rate": "Merged",
        "year_founded": "2004",
        "headquarters": "Irvine, CA",
        "funding_total": "$100M+",
        "latest_round": "Merged with PatientPop",
        "pe_vc_backers": "PE Backed",
        "website_traffic": "200K+",
        "social_following": "20K+",
        "recent_launches": "Tebra rebrand",
        "news_mentions": "15",
    },
    {
        "name": "SimplePractice",
        "website": "https://www.simplepractice.com",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Subscription",
        "base_price": "$29",
        "price_unit": "per month starting",
        "product_categories": "PM; Intake; Telehealth",
        "key_features": "Practice management, Telehealth, Client portal, Billing",
        "integration_partners": "Limited to behavioral health",
        "certifications": "HIPAA",
        "target_segments": "Behavioral Health; Solo",
        "customer_size_focus": "Solo",
        "geographic_focus": "US",
        "customer_count": "100000+",
        "customer_acquisition_rate": "Very high",
        "key_customers": "Testimonials",
        "g2_rating": "4.6",
        "employee_count": "500+",
        "employee_growth_rate": "20% YoY",
        "year_founded": "2012",
        "headquarters": "Los Angeles, CA",
        "funding_total": "$50M+",
        "latest_round": "Series B",
        "pe_vc_backers": "Insight Partners",
        "website_traffic": "400K+",
        "social_following": "100K+",
        "recent_launches": "AI notes",
        "news_mentions": "10",
    },
    {
        "name": "NextGen Healthcare",
        "website": "https://www.nextgen.com",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Enterprise",
        "base_price": "Custom",
        "price_unit": "custom pricing",
        "product_categories": "EHR; PM; RCM",
        "key_features": "Enterprise EHR, Population health, RCM, Interoperability",
        "integration_partners": "Own ecosystem",
        "certifications": "All major",
        "target_segments": "Ambulatory; Specialty",
        "customer_size_focus": "Large (50+)",
        "geographic_focus": "US National",
        "customer_count": "100000+",
        "customer_acquisition_rate": "Enterprise sales",
        "key_customers": "Health systems",
        "g2_rating": "3.8",
        "employee_count": "3000+",
        "employee_growth_rate": "5% YoY",
        "year_founded": "1974",
        "headquarters": "Atlanta, GA",
        "funding_total": "$500M+",
        "latest_round": "Public (NASDAQ: NXGN)",
        "pe_vc_backers": "Public",
        "website_traffic": "300K+",
        "social_following": "20K+",
        "recent_launches": "Platform updates",
        "news_mentions": "30",
    },
    {
        "name": "Solutionreach",
        "website": "https://www.solutionreach.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Per Location",
        "base_price": "$299",
        "price_unit": "per location/month",
        "product_categories": "Patient Engagement; Reminders",
        "key_features": "Appointment reminders, Reviews, Recalls, Two-way texting",
        "integration_partners": "Many EHR/PM systems",
        "certifications": "HIPAA",
        "target_segments": "Multi-specialty; Dental",
        "customer_size_focus": "Medium (15-50)",
        "geographic_focus": "US National",
        "customer_count": "25000+",
        "customer_acquisition_rate": "Good",
        "key_customers": "Many logos",
        "g2_rating": "4.2",
        "employee_count": "400+",
        "employee_growth_rate": "10% YoY",
        "year_founded": "2000",
        "headquarters": "Lehi, UT",
        "funding_total": "$50M+",
        "latest_round": "PE Owned",
        "pe_vc_backers": "Marlin Equity",
        "website_traffic": "75K+",
        "social_following": "10K+",
        "recent_launches": "AI messaging",
        "news_mentions": "12",
    },
    {
        "name": "Luma Health",
        "website": "https://www.lumahealth.io",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Per Location",
        "base_price": "Unknown",
        "price_unit": "per location",
        "product_categories": "Patient Engagement; Scheduling",
        "key_features": "Patient scheduling, Referral management, Waitlist, Communication",
        "integration_partners": "Major EHRs",
        "certifications": "HIPAA",
        "target_segments": "Health Systems; Specialty",
        "customer_size_focus": "Medium (15-50)",
        "geographic_focus": "US National",
        "customer_count": "300+",
        "customer_acquisition_rate": "Growing",
        "key_customers": "Health systems",
        "g2_rating": "4.8",
        "employee_count": "200+",
        "employee_growth_rate": "Growing",
        "year_founded": "2015",
        "headquarters": "San Francisco, CA",
        "funding_total": "$50M+",
        "latest_round": "Series C",
        "pe_vc_backers": "VC Backed",
        "website_traffic": "30K+",
        "social_following": "5K",
        "recent_launches": "AI scheduling",
        "news_mentions": "8",
    },
    {
        "name": "CareCloud",
        "website": "https://www.carecloud.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Per Provider",
        "base_price": "$300",
        "price_unit": "per provider/month",
        "product_categories": "EHR; PM; RCM",
        "key_features": "Cloud EHR, Practice management, Revenue cycle, Analytics",
        "integration_partners": "Own platform",
        "certifications": "HIPAA; SOC2",
        "target_segments": "Multi-specialty",
        "customer_size_focus": "Medium (15-50)",
        "geographic_focus": "US National",
        "customer_count": "5000+",
        "customer_acquisition_rate": "Moderate",
        "key_customers": "On website",
        "g2_rating": "3.9",
        "employee_count": "500+",
        "employee_growth_rate": "5% YoY",
        "year_founded": "2009",
        "headquarters": "Somerset, NJ",
        "funding_total": "$100M+",
        "latest_round": "Public (NASDAQ: CCLD)",
        "pe_vc_backers": "Public",
        "website_traffic": "30K+",
        "social_following": "5K",
        "recent_launches": "Platform updates",
        "news_mentions": "10",
    },
    # ============== NEW COMPETITORS (Additional 32 to reach 40+) ==============
    {
        "name": "Kyruus",
        "website": "https://www.kyruus.com",
        "status": "Active",
        "threat_level": "High",
        "pricing_model": "Enterprise",
        "base_price": "Custom",
        "price_unit": "enterprise pricing",
        "product_categories": "Patient Access; Provider Search; Scheduling",
        "key_features": "Provider matching, Online scheduling, Network optimization, Access analytics",
        "integration_partners": "Epic; Cerner; Athena",
        "certifications": "HIPAA; SOC2",
        "target_segments": "Health Systems; Enterprise",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "500+",
        "customer_acquisition_rate": "Strong",
        "key_customers": "Major health systems",
        "g2_rating": "4.4",
        "employee_count": "400+",
        "employee_growth_rate": "15% YoY",
        "year_founded": "2010",
        "headquarters": "Boston, MA",
        "funding_total": "$100M+",
        "latest_round": "Series D",
        "pe_vc_backers": "VC Backed",
        "website_traffic": "50K+",
        "social_following": "10K+",
        "recent_launches": "AI-powered provider matching",
        "news_mentions": "15",
    },
    {
        "name": "athenahealth",
        "website": "https://www.athenahealth.com",
        "status": "Active",
        "threat_level": "High",
        "pricing_model": "Percentage",
        "base_price": "3-7%",
        "price_unit": "of collections",
        "product_categories": "EHR; PM; RCM; Patient Engagement",
        "key_features": "Cloud EHR, Revenue cycle, Patient portal, Telehealth",
        "integration_partners": "Marketplace integrations",
        "certifications": "HIPAA; SOC2; HITRUST",
        "target_segments": "Ambulatory; Multi-specialty",
        "customer_size_focus": "All Sizes",
        "geographic_focus": "US National",
        "customer_count": "100000+",
        "customer_acquisition_rate": "High",
        "key_customers": "Major health systems",
        "g2_rating": "4.0",
        "employee_count": "5000+",
        "employee_growth_rate": "10% YoY",
        "year_founded": "1997",
        "headquarters": "Watertown, MA",
        "funding_total": "$500M+",
        "latest_round": "PE Owned",
        "pe_vc_backers": "Bain Capital; Hellman & Friedman",
        "website_traffic": "1M+",
        "social_following": "50K+",
        "recent_launches": "athenaOne platform",
        "news_mentions": "50",
    },
    {
        "name": "DrChrono",
        "website": "https://www.drchrono.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Per Provider",
        "base_price": "$199",
        "price_unit": "per provider/month",
        "product_categories": "EHR; PM; Intake; RCM",
        "key_features": "iPad-first EHR, Patient check-in, E-prescribing, Telehealth",
        "integration_partners": "Box; Stripe; Apple",
        "certifications": "HIPAA; ONC Certified",
        "target_segments": "Independent Practices; Specialty",
        "customer_size_focus": "Small (1-15)",
        "geographic_focus": "US National",
        "customer_count": "50000+",
        "customer_acquisition_rate": "High",
        "key_customers": "Specialty practices",
        "g2_rating": "4.0",
        "employee_count": "200+",
        "employee_growth_rate": "15% YoY",
        "year_founded": "2009",
        "headquarters": "Sunnyvale, CA",
        "funding_total": "$50M+",
        "latest_round": "Acquired by EverHealth",
        "pe_vc_backers": "EverHealth",
        "website_traffic": "100K+",
        "social_following": "15K+",
        "recent_launches": "AI documentation",
        "news_mentions": "12",
    },
    {
        "name": "Relatient",
        "website": "https://www.relatient.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Per Location",
        "base_price": "$300",
        "price_unit": "per location/month",
        "product_categories": "Patient Engagement; Scheduling; Intake",
        "key_features": "Self-scheduling, Digital intake, Reminders, Wait list management",
        "integration_partners": "Epic; Cerner; athena",
        "certifications": "HIPAA",
        "target_segments": "Health Systems; Large Practices",
        "customer_size_focus": "Large (50+)",
        "geographic_focus": "US National",
        "customer_count": "500+",
        "customer_acquisition_rate": "Growing",
        "key_customers": "Health systems",
        "g2_rating": "4.3",
        "employee_count": "200+",
        "employee_growth_rate": "20% YoY",
        "year_founded": "2014",
        "headquarters": "Franklin, TN",
        "funding_total": "$30M+",
        "latest_round": "Series B",
        "pe_vc_backers": "VC Backed",
        "website_traffic": "20K+",
        "social_following": "5K+",
        "recent_launches": "AI-powered scheduling",
        "news_mentions": "8",
    },
    {
        "name": "Mend",
        "website": "https://www.mend.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Per Provider",
        "base_price": "$150",
        "price_unit": "per provider/month",
        "product_categories": "Telehealth; Patient Engagement; Intake",
        "key_features": "Video visits, Digital forms, Appointment reminders, No-show prediction",
        "integration_partners": "Most major EHRs",
        "certifications": "HIPAA; SOC2",
        "target_segments": "Multi-specialty; Mental Health",
        "customer_size_focus": "Medium (15-50)",
        "geographic_focus": "US National",
        "customer_count": "700+",
        "customer_acquisition_rate": "Growing",
        "key_customers": "Mental health practices",
        "g2_rating": "4.5",
        "employee_count": "150+",
        "employee_growth_rate": "25% YoY",
        "year_founded": "2014",
        "headquarters": "Orlando, FL",
        "funding_total": "$20M+",
        "latest_round": "Series A",
        "pe_vc_backers": "VC Backed",
        "website_traffic": "30K+",
        "social_following": "3K+",
        "recent_launches": "AI no-show prediction",
        "news_mentions": "6",
    },
    {
        "name": "Klara",
        "website": "https://www.klara.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Per Provider",
        "base_price": "$200",
        "price_unit": "per provider/month",
        "product_categories": "Patient Communication; Intake; Telehealth",
        "key_features": "Secure messaging, Digital intake, Video visits, Team collaboration",
        "integration_partners": "Most major EHRs",
        "certifications": "HIPAA",
        "target_segments": "Specialty Practices; Dermatology",
        "customer_size_focus": "Small (1-15)",
        "geographic_focus": "US National",
        "customer_count": "500+",
        "customer_acquisition_rate": "Growing",
        "key_customers": "Specialty practices",
        "g2_rating": "4.6",
        "employee_count": "100+",
        "employee_growth_rate": "30% YoY",
        "year_founded": "2013",
        "headquarters": "New York, NY",
        "funding_total": "$20M+",
        "latest_round": "Series A",
        "pe_vc_backers": "FirstMark Capital",
        "website_traffic": "25K+",
        "social_following": "3K+",
        "recent_launches": "Team inbox",
        "news_mentions": "5",
    },
    {
        "name": "Notable Health",
        "website": "https://www.notablehealth.com",
        "status": "Active",
        "threat_level": "High",
        "pricing_model": "Enterprise",
        "base_price": "Custom",
        "price_unit": "enterprise pricing",
        "product_categories": "Digital Intake; Automation; AI",
        "key_features": "Pre-visit automation, AI-powered intake, Clinical documentation, Prior auth",
        "integration_partners": "Epic; Cerner",
        "certifications": "HIPAA; SOC2",
        "target_segments": "Health Systems; Enterprise",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "100+",
        "customer_acquisition_rate": "Fast growing",
        "key_customers": "Major health systems",
        "g2_rating": "4.7",
        "employee_count": "300+",
        "employee_growth_rate": "50% YoY",
        "year_founded": "2017",
        "headquarters": "San Mateo, CA",
        "funding_total": "$100M+",
        "latest_round": "Series B",
        "pe_vc_backers": "a16z; OMERS Ventures",
        "website_traffic": "15K+",
        "social_following": "5K+",
        "recent_launches": "AI clinical automation",
        "news_mentions": "20",
    },
    {
        "name": "Qure4u",
        "website": "https://www.qure4u.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Per Provider",
        "base_price": "$200",
        "price_unit": "per provider/month",
        "product_categories": "Patient Engagement; Virtual Care; RPM",
        "key_features": "Virtual visits, Remote patient monitoring, Digital front door, Care navigation",
        "integration_partners": "Major EHRs",
        "certifications": "HIPAA",
        "target_segments": "Health Systems; Specialty",
        "customer_size_focus": "Medium (15-50)",
        "geographic_focus": "US National",
        "customer_count": "400+",
        "customer_acquisition_rate": "Growing",
        "key_customers": "Health systems",
        "g2_rating": "4.3",
        "employee_count": "100+",
        "employee_growth_rate": "20% YoY",
        "year_founded": "2016",
        "headquarters": "Durham, NC",
        "funding_total": "$15M+",
        "latest_round": "Series A",
        "pe_vc_backers": "VC Backed",
        "website_traffic": "10K+",
        "social_following": "2K+",
        "recent_launches": "RPM platform",
        "news_mentions": "5",
    },
    {
        "name": "Yosi Health",
        "website": "https://www.yosi.health",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Per Provider",
        "base_price": "$150",
        "price_unit": "per provider/month",
        "product_categories": "Digital Intake; Patient Engagement",
        "key_features": "Mobile check-in, Pre-registration, Insurance verification, Wait time",
        "integration_partners": "70+ EHR integrations",
        "certifications": "HIPAA",
        "target_segments": "Multi-specialty; Ambulatory",
        "customer_size_focus": "Medium (15-50)",
        "geographic_focus": "US National",
        "customer_count": "300+",
        "customer_acquisition_rate": "Growing",
        "key_customers": "Multi-specialty groups",
        "g2_rating": "4.5",
        "employee_count": "50+",
        "employee_growth_rate": "25% YoY",
        "year_founded": "2015",
        "headquarters": "New York, NY",
        "funding_total": "$5M+",
        "latest_round": "Seed",
        "pe_vc_backers": "VC Backed",
        "website_traffic": "5K+",
        "social_following": "1K+",
        "recent_launches": "Mobile-first check-in",
        "news_mentions": "3",
    },
    {
        "name": "Tebra (PatientPop)",
        "website": "https://www.patientpop.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Per Location",
        "base_price": "$500",
        "price_unit": "per location/month",
        "product_categories": "Practice Growth; Patient Engagement; Reviews",
        "key_features": "Practice marketing, Online reputation, Patient acquisition, Website",
        "integration_partners": "Major PM systems",
        "certifications": "HIPAA",
        "target_segments": "Independent Practices",
        "customer_size_focus": "Small (1-15)",
        "geographic_focus": "US National",
        "customer_count": "10000+",
        "customer_acquisition_rate": "High",
        "key_customers": "Independent practices",
        "g2_rating": "4.0",
        "employee_count": "500+",
        "employee_growth_rate": "Merged",
        "year_founded": "2014",
        "headquarters": "Santa Monica, CA",
        "funding_total": "$75M+",
        "latest_round": "Merged with Kareo",
        "pe_vc_backers": "Toba Capital",
        "website_traffic": "150K+",
        "social_following": "10K+",
        "recent_launches": "Unified Tebra platform",
        "news_mentions": "10",
    },
    {
        "name": "Bridge Patient Portal",
        "website": "https://www.bridgepatientportal.com",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Per Provider",
        "base_price": "$100",
        "price_unit": "per provider/month",
        "product_categories": "Patient Portal; Engagement",
        "key_features": "Patient portal, Secure messaging, Appointment requests, Bill pay",
        "integration_partners": "Multiple EHRs",
        "certifications": "HIPAA",
        "target_segments": "Small Practices; FQHCs",
        "customer_size_focus": "Small (1-15)",
        "geographic_focus": "US National",
        "customer_count": "200+",
        "customer_acquisition_rate": "Steady",
        "key_customers": "FQHCs",
        "g2_rating": "4.4",
        "employee_count": "50+",
        "employee_growth_rate": "10% YoY",
        "year_founded": "2012",
        "headquarters": "Dallas, TX",
        "funding_total": "$5M+",
        "latest_round": "Private",
        "pe_vc_backers": "Private",
        "website_traffic": "5K+",
        "social_following": "1K+",
        "recent_launches": "Mobile app update",
        "news_mentions": "2",
    },
    {
        "name": "Stax Bill",
        "website": "https://www.staxpayments.com",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Transaction",
        "base_price": "2.6%",
        "price_unit": "per transaction",
        "product_categories": "Payments; Billing",
        "key_features": "Payment processing, Recurring billing, Text-to-pay",
        "integration_partners": "Various PM systems",
        "certifications": "PCI-DSS; HIPAA",
        "target_segments": "Healthcare; Multi-industry",
        "customer_size_focus": "All Sizes",
        "geographic_focus": "US National",
        "customer_count": "10000+",
        "customer_acquisition_rate": "High",
        "key_customers": "Multi-industry",
        "g2_rating": "4.2",
        "employee_count": "300+",
        "employee_growth_rate": "20% YoY",
        "year_founded": "2014",
        "headquarters": "Orlando, FL",
        "funding_total": "$100M+",
        "latest_round": "PE Backed",
        "pe_vc_backers": "Growth equity",
        "website_traffic": "50K+",
        "social_following": "5K+",
        "recent_launches": "Healthcare focus",
        "news_mentions": "8",
    },
    {
        "name": "Rectangle Health",
        "website": "https://www.rectanglehealth.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Transaction",
        "base_price": "2.5%",
        "price_unit": "per transaction",
        "product_categories": "Payments; Patient Financing",
        "key_features": "Payment processing, Text-to-pay, Payment plans, Patient financing",
        "integration_partners": "Major PM systems",
        "certifications": "PCI-DSS; HIPAA",
        "target_segments": "Dental; Medical; Specialty",
        "customer_size_focus": "Medium (15-50)",
        "geographic_focus": "US National",
        "customer_count": "50000+",
        "customer_acquisition_rate": "Strong",
        "key_customers": "Multi-specialty",
        "g2_rating": "4.5",
        "employee_count": "200+",
        "employee_growth_rate": "15% YoY",
        "year_founded": "1992",
        "headquarters": "Enfield, CT",
        "funding_total": "$50M+",
        "latest_round": "PE Backed",
        "pe_vc_backers": "Pamlico Capital",
        "website_traffic": "25K+",
        "social_following": "3K+",
        "recent_launches": "Practice management suite",
        "news_mentions": "6",
    },
    {
        "name": "Instruemd",
        "website": "https://www.instamed.com",
        "status": "Acquired",
        "threat_level": "Medium",
        "pricing_model": "Transaction",
        "base_price": "2.9%",
        "price_unit": "per transaction",
        "product_categories": "Payments; RCM",
        "key_features": "Healthcare payments network, Consumer payments, Payer payments",
        "integration_partners": "Wide network",
        "certifications": "PCI-DSS; HIPAA; HITRUST",
        "target_segments": "Health Systems; Payers",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "50000+",
        "customer_acquisition_rate": "Strong",
        "key_customers": "Health systems; payers",
        "g2_rating": "4.1",
        "employee_count": "500+",
        "employee_growth_rate": "Acquired",
        "year_founded": "2004",
        "headquarters": "Philadelphia, PA",
        "funding_total": "$200M+",
        "latest_round": "Acquired by JP Morgan",
        "pe_vc_backers": "JP Morgan",
        "website_traffic": "30K+",
        "social_following": "5K+",
        "recent_launches": "JP Morgan integration",
        "news_mentions": "15",
    },
    {
        "name": "Waystar",
        "website": "https://www.waystar.com",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Enterprise",
        "base_price": "Custom",
        "price_unit": "enterprise pricing",
        "product_categories": "RCM; Payments; Claim Management",
        "key_features": "Revenue cycle automation, Claims management, Payment optimization",
        "integration_partners": "Major EHRs",
        "certifications": "HIPAA; SOC2; HITRUST",
        "target_segments": "Health Systems; Large Practices",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "10000+",
        "customer_acquisition_rate": "Strong",
        "key_customers": "Major health systems",
        "g2_rating": "4.0",
        "employee_count": "2000+",
        "employee_growth_rate": "15% YoY",
        "year_founded": "2017",
        "headquarters": "Louisville, KY",
        "funding_total": "$500M+",
        "latest_round": "IPO Filed",
        "pe_vc_backers": "Bain Capital",
        "website_traffic": "50K+",
        "social_following": "10K+",
        "recent_launches": "AI-powered RCM",
        "news_mentions": "25",
    },
    {
        "name": "Azalea Health",
        "website": "https://www.azaleahealth.com",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Per Provider",
        "base_price": "$400",
        "price_unit": "per provider/month",
        "product_categories": "EHR; PM; RCM; Telehealth",
        "key_features": "Rural health EHR, Practice management, Telehealth, RCM services",
        "integration_partners": "Own ecosystem",
        "certifications": "HIPAA; ONC Certified",
        "target_segments": "Rural Health; FQHCs",
        "customer_size_focus": "Small (1-15)",
        "geographic_focus": "US National",
        "customer_count": "500+",
        "customer_acquisition_rate": "Steady",
        "key_customers": "Rural health clinics",
        "g2_rating": "4.2",
        "employee_count": "100+",
        "employee_growth_rate": "10% YoY",
        "year_founded": "2008",
        "headquarters": "Atlanta, GA",
        "funding_total": "$30M+",
        "latest_round": "Private",
        "pe_vc_backers": "Private",
        "website_traffic": "10K+",
        "social_following": "2K+",
        "recent_launches": "Telehealth expansion",
        "news_mentions": "3",
    },
    {
        "name": "ModMed",
        "website": "https://www.modmed.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Per Provider",
        "base_price": "$500",
        "price_unit": "per provider/month",
        "product_categories": "EHR; PM; RCM; Analytics",
        "key_features": "Specialty-specific EHR, Practice analytics, RCM, Patient engagement",
        "integration_partners": "Specialty-focused",
        "certifications": "HIPAA; ONC Certified",
        "target_segments": "Specialty Practices; Dermatology; Orthopedics",
        "customer_size_focus": "Medium (15-50)",
        "geographic_focus": "US National",
        "customer_count": "20000+",
        "customer_acquisition_rate": "Strong",
        "key_customers": "Specialty practices",
        "g2_rating": "4.3",
        "employee_count": "800+",
        "employee_growth_rate": "25% YoY",
        "year_founded": "2010",
        "headquarters": "Boca Raton, FL",
        "funding_total": "$250M+",
        "latest_round": "Series D",
        "pe_vc_backers": "Warburg Pincus",
        "website_traffic": "75K+",
        "social_following": "15K+",
        "recent_launches": "AI documentation",
        "news_mentions": "18",
    },
    {
        "name": "eClinicalWorks",
        "website": "https://www.eclinicalworks.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Per Provider",
        "base_price": "$450",
        "price_unit": "per provider/month",
        "product_categories": "EHR; PM; RCM; Population Health",
        "key_features": "Ambulatory EHR, Practice management, Population health, Telehealth",
        "integration_partners": "Own ecosystem",
        "certifications": "HIPAA; ONC Certified",
        "target_segments": "Ambulatory; Community Health",
        "customer_size_focus": "All Sizes",
        "geographic_focus": "US National",
        "customer_count": "150000+",
        "customer_acquisition_rate": "High",
        "key_customers": "Community health centers",
        "g2_rating": "3.6",
        "employee_count": "5000+",
        "employee_growth_rate": "10% YoY",
        "year_founded": "1999",
        "headquarters": "Westborough, MA",
        "funding_total": "Private",
        "latest_round": "Private",
        "pe_vc_backers": "Private",
        "website_traffic": "200K+",
        "social_following": "25K+",
        "recent_launches": "V12 platform",
        "news_mentions": "30",
    },
    {
        "name": "Greenway Health",
        "website": "https://www.greenwayhealth.com",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Per Provider",
        "base_price": "$400",
        "price_unit": "per provider/month",
        "product_categories": "EHR; PM; RCM",
        "key_features": "Ambulatory EHR, Practice management, Revenue cycle, Analytics",
        "integration_partners": "Own ecosystem",
        "certifications": "HIPAA; ONC Certified",
        "target_segments": "Ambulatory; Multi-specialty",
        "customer_size_focus": "Medium (15-50)",
        "geographic_focus": "US National",
        "customer_count": "10000+",
        "customer_acquisition_rate": "Moderate",
        "key_customers": "Multi-specialty groups",
        "g2_rating": "3.5",
        "employee_count": "1000+",
        "employee_growth_rate": "5% YoY",
        "year_founded": "1998",
        "headquarters": "Tampa, FL",
        "funding_total": "$200M+",
        "latest_round": "PE Owned",
        "pe_vc_backers": "Vista Equity",
        "website_traffic": "50K+",
        "social_following": "10K+",
        "recent_launches": "Intergy updates",
        "news_mentions": "10",
    },
    {
        "name": "Experian Health",
        "website": "https://www.experian.com/healthcare",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Enterprise",
        "base_price": "Custom",
        "price_unit": "enterprise pricing",
        "product_categories": "RCM; Patient Access; Identity",
        "key_features": "Identity verification, Eligibility, Patient estimates, Collections",
        "integration_partners": "Major health IT",
        "certifications": "HIPAA; SOC2",
        "target_segments": "Health Systems; Enterprise",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "10000+",
        "customer_acquisition_rate": "Enterprise sales",
        "key_customers": "Major health systems",
        "g2_rating": "4.0",
        "employee_count": "1000+",
        "employee_growth_rate": "10% YoY",
        "year_founded": "2015",
        "headquarters": "Franklin, TN",
        "funding_total": "Public company division",
        "latest_round": "N/A",
        "pe_vc_backers": "Experian (Public)",
        "website_traffic": "100K+",
        "social_following": "10K+",
        "recent_launches": "Patient access suite",
        "news_mentions": "15",
    },
    {
        "name": "Olive AI",
        "website": "https://www.oliveai.com",
        "status": "Acquired",
        "threat_level": "Low",
        "pricing_model": "Enterprise",
        "base_price": "Custom",
        "price_unit": "enterprise pricing",
        "product_categories": "Healthcare Automation; AI; RCM",
        "key_features": "Revenue cycle automation, Prior auth automation, Claims processing",
        "integration_partners": "Major health IT",
        "certifications": "HIPAA; SOC2",
        "target_segments": "Health Systems; Payers",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "100+",
        "customer_acquisition_rate": "Restructured",
        "key_customers": "Health systems",
        "g2_rating": "3.8",
        "employee_count": "300+",
        "employee_growth_rate": "Restructured",
        "year_founded": "2012",
        "headquarters": "Columbus, OH",
        "funding_total": "$400M+",
        "latest_round": "Acquired/Split",
        "pe_vc_backers": "Various",
        "website_traffic": "20K+",
        "social_following": "5K+",
        "recent_launches": "Prior auth automation",
        "news_mentions": "20",
    },
    {
        "name": "WELL Health",
        "website": "https://www.wellapp.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Per Location",
        "base_price": "$400",
        "price_unit": "per location/month",
        "product_categories": "Patient Communication; Engagement",
        "key_features": "Omnichannel communication, Appointment reminders, Broadcast messaging",
        "integration_partners": "Major EHRs",
        "certifications": "HIPAA; SOC2",
        "target_segments": "Health Systems; Large Practices",
        "customer_size_focus": "Large (50+)",
        "geographic_focus": "US National",
        "customer_count": "500+",
        "customer_acquisition_rate": "Growing",
        "key_customers": "Health systems",
        "g2_rating": "4.6",
        "employee_count": "200+",
        "employee_growth_rate": "30% YoY",
        "year_founded": "2015",
        "headquarters": "Santa Barbara, CA",
        "funding_total": "$75M+",
        "latest_round": "Series C",
        "pe_vc_backers": "Insight Partners",
        "website_traffic": "15K+",
        "social_following": "3K+",
        "recent_launches": "AI-powered messaging",
        "news_mentions": "10",
    },
    {
        "name": "Artera (WELL)",
        "website": "https://www.artera.io",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Per Location",
        "base_price": "$500",
        "price_unit": "per location/month",
        "product_categories": "Patient Communication; Digital Engagement",
        "key_features": "Unified patient communication, Orchestration, Broadcast, Conversational AI",
        "integration_partners": "Epic; Cerner; athena",
        "certifications": "HIPAA; SOC2; HITRUST",
        "target_segments": "Health Systems; Enterprise",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "700+",
        "customer_acquisition_rate": "Fast growing",
        "key_customers": "Major health systems",
        "g2_rating": "4.7",
        "employee_count": "300+",
        "employee_growth_rate": "40% YoY",
        "year_founded": "2015",
        "headquarters": "Santa Barbara, CA",
        "funding_total": "$138M+",
        "latest_round": "Series C",
        "pe_vc_backers": "Insight Partners; General Catalyst",
        "website_traffic": "20K+",
        "social_following": "5K+",
        "recent_launches": "Artera Harmony",
        "news_mentions": "25",
    },
    {
        "name": "Symplr",
        "website": "https://www.symplr.com",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Enterprise",
        "base_price": "Custom",
        "price_unit": "enterprise pricing",
        "product_categories": "Healthcare Operations; Compliance; Workforce",
        "key_features": "Provider credentialing, Compliance management, Workforce management",
        "integration_partners": "Major health IT",
        "certifications": "HIPAA; SOC2",
        "target_segments": "Health Systems; Enterprise",
        "customer_size_focus": "Enterprise",
        "geographic_focus": "US National",
        "customer_count": "3000+",
        "customer_acquisition_rate": "Enterprise sales",
        "key_customers": "Health systems",
        "g2_rating": "3.8",
        "employee_count": "2000+",
        "employee_growth_rate": "15% YoY",
        "year_founded": "2006",
        "headquarters": "Houston, TX",
        "funding_total": "$500M+",
        "latest_round": "PE Backed",
        "pe_vc_backers": "Clearlake Capital",
        "website_traffic": "50K+",
        "social_following": "10K+",
        "recent_launches": "Unified platform",
        "news_mentions": "15",
    },
    {
        "name": "RXNT",
        "website": "https://www.rxnt.com",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Per Provider",
        "base_price": "$150",
        "price_unit": "per provider/month",
        "product_categories": "EHR; PM; E-Prescribing",
        "key_features": "Cloud EHR, E-prescribing, Practice management, Patient portal",
        "integration_partners": "Limited",
        "certifications": "HIPAA; ONC Certified",
        "target_segments": "Small Practices",
        "customer_size_focus": "Small (1-15)",
        "geographic_focus": "US National",
        "customer_count": "5000+",
        "customer_acquisition_rate": "Moderate",
        "key_customers": "Small practices",
        "g2_rating": "4.0",
        "employee_count": "100+",
        "employee_growth_rate": "10% YoY",
        "year_founded": "1999",
        "headquarters": "Annapolis, MD",
        "funding_total": "Private",
        "latest_round": "Private",
        "pe_vc_backers": "Private",
        "website_traffic": "15K+",
        "social_following": "2K+",
        "recent_launches": "Cloud updates",
        "news_mentions": "3",
    },
    {
        "name": "Office Ally",
        "website": "https://www.officeally.com",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Free/Freemium",
        "base_price": "Free",
        "price_unit": "free basic tier",
        "product_categories": "PM; Claims; Clearinghouse",
        "key_features": "Free practice management, Claims submission, EHR, Patient statements",
        "integration_partners": "Open ecosystem",
        "certifications": "HIPAA",
        "target_segments": "Small Practices; Solo",
        "customer_size_focus": "Solo",
        "geographic_focus": "US National",
        "customer_count": "80000+",
        "customer_acquisition_rate": "Very high",
        "key_customers": "Small practices",
        "g2_rating": "4.3",
        "employee_count": "300+",
        "employee_growth_rate": "15% YoY",
        "year_founded": "2000",
        "headquarters": "Vancouver, WA",
        "funding_total": "Private",
        "latest_round": "Private",
        "pe_vc_backers": "Private",
        "website_traffic": "100K+",
        "social_following": "5K+",
        "recent_launches": "EHR 24/7 updates",
        "news_mentions": "5",
    },
    {
        "name": "Modernizing Medicine (ModMed)",
        "website": "https://www.modmed.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Per Provider",
        "base_price": "$450",
        "price_unit": "per provider/month",
        "product_categories": "Specialty EHR; PM; Analytics",
        "key_features": "Specialty-specific EHR, Practice analytics, Patient engagement",
        "integration_partners": "Specialty ecosystems",
        "certifications": "HIPAA; ONC Certified",
        "target_segments": "Dermatology; Ophthalmology; Orthopedics",
        "customer_size_focus": "Medium (15-50)",
        "geographic_focus": "US National",
        "customer_count": "30000+",
        "customer_acquisition_rate": "Strong",
        "key_customers": "Specialist physicians",
        "g2_rating": "4.2",
        "employee_count": "1000+",
        "employee_growth_rate": "20% YoY",
        "year_founded": "2010",
        "headquarters": "Boca Raton, FL",
        "funding_total": "$300M+",
        "latest_round": "PE Backed",
        "pe_vc_backers": "Warburg Pincus",
        "website_traffic": "60K+",
        "social_following": "12K+",
        "recent_launches": "EMA AI features",
        "news_mentions": "15",
    },
    {
        "name": "Petal Health",
        "website": "https://www.petalmd.com",
        "status": "Active",
        "threat_level": "Low",
        "pricing_model": "Per Provider",
        "base_price": "$75",
        "price_unit": "per provider/month",
        "product_categories": "Scheduling; Workforce; Communication",
        "key_features": "Physician scheduling, On-call management, Secure messaging",
        "integration_partners": "Major EHRs",
        "certifications": "HIPAA",
        "target_segments": "Hospitals; Physician Groups",
        "customer_size_focus": "Large (50+)",
        "geographic_focus": "North America",
        "customer_count": "300+",
        "customer_acquisition_rate": "Growing",
        "key_customers": "Hospitals",
        "g2_rating": "4.5",
        "employee_count": "100+",
        "employee_growth_rate": "25% YoY",
        "year_founded": "2013",
        "headquarters": "Quebec, Canada",
        "funding_total": "$30M+",
        "latest_round": "Series B",
        "pe_vc_backers": "iNovia Capital",
        "website_traffic": "10K+",
        "social_following": "2K+",
        "recent_launches": "Mobile updates",
        "news_mentions": "5",
    },
    {
        "name": "Healow (eCW)",
        "website": "https://www.healow.com",
        "status": "Active",
        "threat_level": "Medium",
        "pricing_model": "Free/Bundled",
        "base_price": "Free",
        "price_unit": "bundled with eCW",
        "product_categories": "Patient Portal; Telehealth; Engagement",
        "key_features": "Patient portal app, Telehealth, Appointment booking, Health records",
        "integration_partners": "eClinicalWorks",
        "certifications": "HIPAA",
        "target_segments": "eCW Customers; Patients",
        "customer_size_focus": "All Sizes",
        "geographic_focus": "US National",
        "customer_count": "100000+",
        "customer_acquisition_rate": "High",
        "key_customers": "eCW practices",
        "g2_rating": "3.8",
        "employee_count": "Part of eCW",
        "employee_growth_rate": "Part of eCW",
        "year_founded": "2010",
        "headquarters": "Westborough, MA",
        "funding_total": "Part of eCW",
        "latest_round": "N/A",
        "pe_vc_backers": "eClinicalWorks",
        "website_traffic": "500K+",
        "social_following": "15K+",
        "recent_launches": "Healow Plus",
        "news_mentions": "10",
    },
]



def seed_database(force: bool = False):
    """Seed the database with initial competitors."""
    db = SessionLocal()
    
    # Combine all competitor lists and deduplicate by name
    all_competitors_raw = COMPETITORS + ADDITIONAL_COMPETITORS_PART1 + ADDITIONAL_COMPETITORS_PART2
    
    # Deduplicate by name (keep first occurrence)
    seen_names = set()
    all_competitors = []
    for comp in all_competitors_raw:
        name = comp.get("name", "").lower()
        if name not in seen_names:
            seen_names.add(name)
            all_competitors.append(comp)
        else:
            print(f"  [DEDUP] Skipping duplicate: {comp.get('name')}")
    
    # Check if already seeded
    existing = db.query(Competitor).count()
    if existing > 0 and not force:
        print(f"Database already has {existing} competitors. Use --force to reseed.")
        db.close()
        return
    
    if force and existing > 0:
        print(f"Force flag set. Deleting {existing} existing competitors...")
        db.query(Competitor).delete()
        db.commit()
    
    # Add competitors
    added = 0
    skipped = 0
    for comp_data in all_competitors:
        try:
            competitor = Competitor(**comp_data)
            db.add(competitor)
            added += 1
        except Exception as e:
            print(f"  Skipped {comp_data.get('name', 'unknown')}: {e}")
            skipped += 1
    
    db.commit()
    print(f"\n{'='*50}")
    print(f"Seeded {added} competitors into database. (Skipped: {skipped})")
    print(f"  - Original list: {len(COMPETITORS)}")
    print(f"  - Part 1 additions: {len(ADDITIONAL_COMPETITORS_PART1)}")
    print(f"  - Part 2 additions: {len(ADDITIONAL_COMPETITORS_PART2)}")
    print(f"  - After deduplication: {len(all_competitors)}")
    print(f"{'='*50}")
    db.close()


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Seed the Certify Intel database")
    parser.add_argument("--force", action="store_true", help="Force reseed (delete existing data)")
    args = parser.parse_args()
    seed_database(force=args.force)
